### PR TITLE
Updated ME to v11.8.81.3781 with NPDM

### PR DESCRIPTION
**Pull request by jjr2000**
Fixes issues brought up by @fefifofum in #31 
ME.bin has been updated and readme to coincide with it.

### CODE REVIEW

**Comment by jjr2000** [comment]
I have further added the newest version of the BIOS into the repo. All flashed ok on my laptop and seems stable thus far.

**Comment by Cr0wTom** [comment]
Any changes with the new update?

**Comment by MarFre22** [comment]
> I have further added the newest version of the BIOS into the repo. All flashed ok on my laptop and seems stable thus far.

Hi, sorry for the question, the newest version has the same keyboard background modes as v906?
And did you find any improvements?
Thanks!

**Comment by jjr2000** [comment]
@MarFre22 If you are asking about KB backlight modes this version has standard and power saver (off after 15 seconds.)

@Cr0wTom New update doesn't appear to have any major changes, will have to wait to see if things like power consumption have been affected.

**Comment by MarFre22** [comment]
@jjr2000 Thanks ;)

**Pull request merged**
